### PR TITLE
Twitter-like data saver mode feature

### PR DESCRIPTION
**Pull request by codeshifu**
screenshot_2018-02-04-21-47-24-1

Show image preview until the user asks for the full image. This helps to reduce the amount of mobile data used in app

### CODE REVIEW

**Comment by ooade** [comment]
This is great 🎉 
You didn't implement for react 😅
Thanks 👍

**Comment by codeshifu** [comment]
will do that asap. cheers

**Comment by ooade** [comment]
Would you mind publishing the new release on npm? 
Yes? Your npm name so I can grant you access.
No? High five :hand:

**Comment by codeshifu** [comment]
codeshifu

**Comment by ooade** [comment]
Done! Go ye into the world and make a new release **v1.0.0-alpha.2**

**Comment by ooade** [comment]
I haven't seen anything yet. Maybe a guide will help:
- Change the version on the package.json
- `npm publish`
Thanks :pray:

**Comment by codeshifu** [comment]
sorry man. Was on a 12hrs journey yesterday coming from Abia to Lagos.

**Comment by codeshifu** [comment]
do you mind creating a new release?

**Comment by ooade** [comment]
Will have to wait till weekend then. My laptop isn't with me.

**Pull request merged**
